ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS customer_email VARCHAR(160),
  ADD COLUMN IF NOT EXISTS customer_name VARCHAR(120),
  ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(40),
  ADD COLUMN IF NOT EXISTS payment_method VARCHAR(40),
  ADD COLUMN IF NOT EXISTS payment_status VARCHAR(20) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(120),
  ADD COLUMN IF NOT EXISTS payment_last4 VARCHAR(4),
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
